"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['view.py']
DATA_FILES = ["assets"]
OPTIONS = {
    'plist': {
        'LSUIElement': True,
    },
    'packages': ['rumps', 'flet', 'ssl', 'macwifi', 'requests', 'urllib3', 'keyring', 'data', 'main'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
